// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNewUser: typeof import('./src/components/AddNewUser.vue')['default']
    AddNewUserComponent: typeof import('./src/components/AddNewUserComponent.vue')['default']
    DeleteUserComponent: typeof import('./src/components/DeleteUserComponent.vue')['default']
    EditUserComponent: typeof import('./src/components/EditUserComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
    UserListComponent: typeof import('./src/components/UserListComponent.vue')['default']
  }
}
